### ISSUE TITLE
Bổ sung nội dung về lập trình an toàn

### ISSUE THREAD

**Issue by lochv** [zalopay-oss/go-advanced#9]
Tôi nghĩ là nên bổ sung thêm phần lập trình an toàn với GO.

**Comment by anhldbk** [comment]
@lochv bạn có thể brainstorming giúp tụi mình phần đấy không? Sẽ rất tuyệt nếu có bạn contribute vào dự án này chung với tụi mình

**Comment by lochv** [comment]
@anhldbk em cũng muốn lắm, nhưng viết lách kém quá.
